id: IC432361A
legacy_id: P007995
ocr_import_info:
  bdrc_scan_id: W1KG1281
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T12:14:40'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:39:49.171881+00:00'
last_modified: 2022-08-31 11:40:15.217479
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG1281
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG1281
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆེ་ཤོས་སྐུ་ཕྲེང་གསུམ་པ་བློ་བཟང་བྱང་ཆུབ་བསྟན་པའི་སྒྲོན་མེའི་རང་རྣམ།
  author: ཆེ་ཤོས ༠༣་བློ་བཟང་བྱང་ཆུབ་བསྟན་པའི་སྒྲོན་མེ།
statistics:
  ocr_word_mean_confidence_index: 0.5530435357896236
  ocr_word_median_confidence_index: 0.550000011920929
quality: null
bases:
  I1KG1283:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1283
      total_pages: 780
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1283.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5530435357896236
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
